#!/usr/bin/env python3
"""Generate a backlog-ready ML package scaffold from the PO Router template."""

from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover
    yaml = None

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_TEMPLATE = ROOT / "doc" / "team_workflow" / "templates" / "ml_package_template.yaml"
DEFAULT_REGISTRY = ROOT / "doc" / "backlog_registry.yaml"


def _load_yaml(path: Path) -> dict[str, Any]:
    if yaml is None:
        raise RuntimeError("PyYAML is required: pip install pyyaml")
    with path.open("r", encoding="utf-8") as fh:
        loaded = yaml.safe_load(fh) or {}
    if not isinstance(loaded, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return loaded


def build_registry_item(
    package_id: str,
    goal: str,
    *,
    wave_id: str = "po-router-ai-completion-wave",
    impact: str = "eval",
    cost_estimate: str = "M",
    priority: str = "P1",
    created: str | None = None,
    depends_on: list[str] | None = None,
) -> dict[str, Any]:
    """Build a minimal backlog_registry.yaml item that passes registry lint."""
    today = created or date.today().isoformat()
    return {
        "id": package_id,
        "wave_id": wave_id,
        "status": "proposed",
        "type": "ml_package",
        "cjm_moments": ["cross-loop"],
        "user_stories": ["US-20.1"],
        "impact": impact,
        "blocks": goal,
        "depends_on": depends_on or [],
        "cost_estimate": cost_estimate,
        "priority": priority,
        "write_set_max": 8,
        "deliverables": [
            f"eval_data/ml_eval/{package_id}/evaluation_contract.yaml",
            f"eval_data/ml_eval/{package_id}/package.yaml",
            f"tests/eval/test_{package_id.replace('-', '_')}.py",
        ],
        "dod_commands": [
            f".\\.venv\\Scripts\\python.exe scripts\\validate_evaluation_contract.py eval_data/ml_eval/{package_id}/evaluation_contract.yaml",
            ".\\.venv\\Scripts\\python.exe scripts\\backlog_registry_lint.py --strict --sync-from-index --write-sync",
        ],
        "read_set_hint": [
            "doc/team_workflow/po_router_evaluation_gate.md",
            "doc/team_workflow/templates/ml_package_template.yaml",
        ],
        "exit_artifact": "Evaluation contract, package scaffold, and fallback policy are review-ready.",
        "re_entry_condition": None,
        "created": today,
        "last_review": today,
        "notes": "Generated by scripts/generate_ml_package_scaffold.py; review before promotion to ready.",
    }


def render_item(item: dict[str, Any]) -> str:
    if yaml is None:
        raise RuntimeError("PyYAML is required: pip install pyyaml")
    return yaml.safe_dump([item], allow_unicode=True, sort_keys=False)


def generate_from_template(
    template_path: Path,
    *,
    package_id: str,
    goal: str,
    wave_id: str,
    created: str | None,
) -> dict[str, Any]:
    template = _load_yaml(template_path)
    if not template.get("package_id") or not template.get("goal"):
        raise ValueError(f"{template_path} is not an ML package template")
    return build_registry_item(package_id, goal, wave_id=wave_id, created=created)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a registry YAML stanza for an ML package.")
    parser.add_argument("--package-id", required=True)
    parser.add_argument("--goal", required=True)
    parser.add_argument("--wave-id", default="po-router-ai-completion-wave")
    parser.add_argument("--created", default=None)
    parser.add_argument("--template", type=Path, default=DEFAULT_TEMPLATE)
    args = parser.parse_args(argv)

    item = generate_from_template(
        args.template,
        package_id=args.package_id,
        goal=args.goal,
        wave_id=args.wave_id,
        created=args.created,
    )
    print(render_item(item), end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
